name: Run Lint and Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  lint-and-test:
    services:
      postgres:
        image: postgres:16.4-alpine
        env:
          POSTGRES_USER: mtc
          POSTGRES_PASSWORD: mtc
          POSTGRES_DB: mtc_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install
        run: make install

      - name: Format
        run: |
          make fmt

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory."
            git diff
            exit 1
          fi

      - name: Lint
        run: make lint

      - name: Test
        run: make test-all
