name: Run Lint and Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install
        run: make install

      - name: Format
        run: |
          make fmt

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory."
            git diff
            exit 1
          fi

      - name: Lint
        run: make lint

      - name: Test
        run: make test-all
